#!/bin/bash
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

SCRIPT_NAME=`realpath $0`
FGLJPDIR=`dirname $SCRIPT_NAME` 
export FGL_LENGTH_SEMANTICS=BYTE
export LC_ALL="en_US.UTF-8"
export FGLGUI=0
#we recompile everything always: hence avoid version clashes
make -C $FGLJPDIR clean_prog all > /dev/null
export FGLJPDIR
exec fglrun $FGLJPDIR/fgljpssh.42m "$@"
