#!/bin/bash
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

SCRIPT_NAME=`realpath $0`
FGLJPDIR=`dirname $SCRIPT_NAME` 
export FGL_LENGTH_SEMANTICS=BYTE
export LC_ALL="en_US.UTF-8"
export FGLGUI=0
#recompile only when needed
source "$FGLJPDIR/myfglcomp.sh"
myfglcomp mygetopt > /dev/null
myfglcomp fgljp > /dev/null
myfglcomp fglssh > /dev/null
export FGLJPDIR
exec fglrun $FGLJPDIR/fglssh.42m "$@"
